import assets from "@/public/assets";
import Beach from "@/public/assets/image/Beach.png";
import Kitchen from "@/public/assets/image/Kitchen.png";
import Livingroom from "@/public/assets/image/Living Room.png";
import LivingRoom from "@/public/assets/image/LivingRoom.png";
import Minimal from "@/public/assets/image/Minimal.png";
import Rocks from "@/public/assets/image/Rocks.png";
import Room from "@/public/assets/image/Room.png";
import Waterfalls from "@/public/assets/image/Waterfalls.png";
export const categoryList = ["Large Appliances", "Apparel & Footwear", "Mobile & Laptops", "Furniture & Decor", "Other" ];

export const placementList = [
  "Mobile",
  "Electronics",
  "Large Items",
  "Furnitures",
];

export const ImgFormate = [
  "png",
  "jpg",
  "webp",
  "avif",

];
export const surroundingList = [
  "Mobile",
  "Electronics",
  "Large Items",
  "Furnitures",
];

export const BackgroundList = [
  "Mobile",
  "Electronics",
  "Large Items",
  "Furnitures",
];
export const coloreMode = ["None", "Add", "Multiply", "Overlay"];
export const Loara = [
  "RealisticNaturalScenery",
  "InteriorDesign",
  "AbstractPattern",
];

export const productSuggestions = ["bottle", "can", "box", "bag", "device"];
export const PlacementSuggestions = [
  "circular platform",
  "circular reflective platform",
  "flower patch",
  "a marble block",
  "a mound of grass",
  "a grassy hill",
];
export const productSuggestionsPrash = [
  "on",
  "standing on",
  "laying on",
  "balancing on",
  "buried in",
  "emerging from",
  "in",
];
export const SurroundedSuggestions = [
  " trees",
  "leaves",
  "autumn leaves",
  "wavy fabrics",
  "dried bark",
  "potted plant",
];
export const SurrontedSuggestionsPrash = ["with", "next to", "surrounded by "];
export const BackgroundSuggestions = [
  "soft shadows",
  "the ocean and blue skies with clouds",
  "desert in the background",
  "marsh with sunlight streaming down in the background",
  "fairy lights in the background",
  "a white circular window",
];
export const BackgrowundSuggestionsPrash = ["in front of", "against", "with"];
export const resultList = [1, 2, 3, 4];

export const renderStrength = [
  {
    tittle: "Extra Weak",
  },
  {
    tittle: "Weak",
  },
  {
    tittle: "Default",
  },
  {
    tittle: "Strong ",
  },
  {
    tittle: "Extra Strong",
  },
];
export const coloreStrength = [
  {
    tittle: "None",
  },
  {
    tittle: "Weak",
  },
  {
    tittle: "Default",
  },
  {
    tittle: "Strong ",
  },
  {
    tittle: "Extra Strong",
  },
];
export const outlineStrength = [
  {
    tittle: "None",
  },
  {
    tittle: "Extra Weak",
  },
  {
    tittle: "Weak",
  },
  {
    tittle: "Default",
  },
  {
    tittle: "Strong ",
  },
  {
    tittle: "Extra Strong",
  },
];

// export const TempletList = [
//   {
//     title: "Indoor Scene ",
//     list: [
//       {
//         title: "Kitchen 1 ",

//         image: "https://ik.imagekit.io/7urmiszfde/Kitchen.png?updatedAt=1697518303106",
//         promt: "In a simple, contemporary kitchen",
//         placementType: "",
//         surroundingType: "",
//         backgroundType: "",
//         product: "",
//         placement: "",
//         surrounding: "",
//         background: "",
//         lora: "RealisticNaturalScenery",
//       },
//       {
//         title: "Kitchen 2 ",

//         image: "https://ik.imagekit.io/7urmiszfde/Kitchen.png?updatedAt=1697518303106",
//         promt: "In a luxury, aesthetic kitchen ",
//         placementType: "",
//         surroundingType: "",
//         backgroundType: "",
//         product: "",
//         placement: "a beach",
//         surrounding: "",
//         background: "",
//         lora: "RealisticNaturalScenery",
//       },
//       {
//         title: "Living Room 1 ",

//         image: "https://ik.imagekit.io/7urmiszfde/Living%20Room.png?updatedAt=1697518302302",
//         promt: "in a luxury, contemporary living room",
//         placementType: "",
//         surroundingType: "",
//         backgroundType: "",
//         product: "",
//         placement: "",
//         surrounding: "",
//         background: "",
//         lora: "RealisticNaturalScenery",
//       },
//       {
//         title: "Living Room 2 ",

//         image: "https://ik.imagekit.io/7urmiszfde/Living%20Room.png?updatedAt=1697518302302",
//         promt: " in a simple, minimalistic living room",
//         placementType: "",
//         surroundingType: "",
//         backgroundType: "",
//         product: "",
//         placement: "a beach",
//         surrounding: "",
//         background: "",
//         lora: "RealisticNaturalScenery",
//       },
//       {
//         title: "Dining 1 ",

//         image: "https://ik.imagekit.io/7urmiszfde/Screenshot%202023-10-17%20102933.png?updatedAt=1697518804744",
//         promt: "in a simple, minimalistic Dining hall",
//         placementType: "",
//         surroundingType: "",
//         backgroundType: "",
//         product: "",
//         placement: "",
//         surrounding: "",
//         background: "",
//         lora: "RealisticNaturalScenery",
//       },
//       {
//         title: "Dining 2 ",

//         image: "https://ik.imagekit.io/7urmiszfde/Screenshot%202023-10-17%20102933.png?updatedAt=1697518804744",
//         promt: "in a luxury, contemporary Dining hall ",
//         placementType: "",
//         surroundingType: "",
//         backgroundType: "",
//         product: "",
//         placement: "a beach",
//         surrounding: "",
//         background: "",
//         lora: "RealisticNaturalScenery",
//       },
//       {
//         title: "Office  1 ",

//         image: "https://ik.imagekit.io/7urmiszfde/image%20(2).png?updatedAt=1697518662396",
//         promt: "in a modern, class office space",
//         placementType: "",
//         surroundingType: "",
//         backgroundType: "",
//         product: "",
//         placement: "",
//         surrounding: "",
//         background: "",
//         lora: "RealisticNaturalScenery",
//       },
//       {
//         title: "Office  2 ",

//         image: "https://ik.imagekit.io/7urmiszfde/image%20(2).png?updatedAt=1697518662396",
//         promt: " in a simple, minimalistic Office space",
//         placementType: "",
//         surroundingType: "",
//         backgroundType: "",
//         product: "",
//         placement: "a beach",
//         surrounding: "",
//         background: "",
//         lora: "RealisticNaturalScenery",
//       },
//       {
//         title: "Bedroom   1 ",

//         image: "https://ik.imagekit.io/7urmiszfde/image%20(3).png?updatedAt=1697518630772",
//         promt: "In a modern, luxury bedroom ",
//         placementType: "",
//         surroundingType: "",
//         backgroundType: "",
//         product: "",
//         placement: "",
//         surrounding: "",
//         background: "",
//         lora: "RealisticNaturalScenery",
//       },
//       {
//         title: "Bedroom 2 ",

//         image: "https://ik.imagekit.io/7urmiszfde/image%20(3).png?updatedAt=1697518630772",
//         promt: " In a simple, minimalistic bedroom ",
//         placementType: "",
//         surroundingType: "",
//         backgroundType: "",
//         product: "",
//         placement: "a beach",
//         surrounding: "",
//         background: "",
//         lora: "RealisticNaturalScenery",
//       }, {
//         title: "House 1 ",

//         image: "https://ik.imagekit.io/7urmiszfde/image%20(4).png?updatedAt=1697518652695",
//         promt: " Inside a simple, traditional, aesthetic house",
//         placementType: "",
//         surroundingType: "",
//         backgroundType: "",
//         product: "",
//         placement: "",
//         surrounding: "",
//         background: "",
//         lora: "RealisticNaturalScenery",
//       },
//       {
//         title: "House 2 ",

//         image: "https://ik.imagekit.io/7urmiszfde/image%20(4).png?updatedAt=1697518652695",
//         promt: " Inside a luxury, modern house",
//         placementType: "",
//         surroundingType: "",
//         backgroundType: "",
//         product: "",
//         placement: "a beach",
//         surrounding: "",
//         background: "",
//         lora: "RealisticNaturalScenery",
//       }, {
//         title: "House 3",

//         image: "https://ik.imagekit.io/7urmiszfde/image%20(4).png?updatedAt=1697518652695",
//         promt: "Inside a minimalistic, contemporary house",
//         placementType: "",
//         surroundingType: "",
//         backgroundType: "",
//         product: "",
//         placement: "",
//         surrounding: "",
//         background: "",
//         lora: "RealisticNaturalScenery",
//       },
      
//     ],
//   },
//   {
//     title: "On Platforms ",
//     list: [
//       {
//         title: "Counter ",

//         image: "https://ik.imagekit.io/7urmiszfde/image%20(5).png?updatedAt=1697518655355",
//         promt: "On a Kitchen Counter",
//         placementType: "on",
//         surroundingType: "",
//         backgroundType: "",
//         product: "",
//         placement: "a beach",
//         surrounding: "",
//         background: "",
//         lora: "RealisticNaturalScenery",
//       },
//       {
//         title: "Office ",

//         image: "https://ik.imagekit.io/7urmiszfde/image%20(5).png?updatedAt=1697518655355",
//         promt: "On an Office Table",
//         placementType: "on",
//         surroundingType: "",
//         backgroundType: "",
//         product: "",
//         placement: "a beach",
//         surrounding: "",
//         background: "",
//         lora: "RealisticNaturalScenery",
//       },
//       {
//         title: "Bench ",

//         image: "https://ik.imagekit.io/7urmiszfde/Untitled%20(15).webp?updatedAt=1697519169587",
//         promt: "On a park bench",
//         placementType: "on",
//         surroundingType: "",
//         backgroundType: "",
//         product: "",
//         placement: "a beach",
//         surrounding: "",
//         background: "",
//         lora: "RealisticNaturalScenery",
//       },
//       {
//         title: "Coffee ",

//         image: "https://ik.imagekit.io/7urmiszfde/Untitled%20(15).webp?updatedAt=1697519169587",
//         promt: "On a Coffee Table",
//         placementType: "on",
//         surroundingType: "",
//         backgroundType: "",
//         product: "",
//         placement: "a beach",
//         surrounding: "",
//         background: "",
//         lora: "RealisticNaturalScenery",
//       },
//       {
//         title: "Photoshoot ",

//         image: "https://ik.imagekit.io/7urmiszfde/Untitled%20(3).png?updatedAt=1697518596819",
//         promt: "On a professional photoshoot pedestal ",
//         placementType: "on",
//         surroundingType: "",
//         backgroundType: "",
//         product: "",
//         placement: "a beach",
//         surrounding: "",
//         background: "",
//         lora: "RealisticNaturalScenery",
//       },
//       {
//         title: "Podium ",

//         image: "https://ik.imagekit.io/7urmiszfde/Untitled%20(3).png?updatedAt=1697518596819",
//         promt: " On a marble podium",
//         placementType: "on",
//         surroundingType: "",
//         backgroundType: "",
//         product: "",
//         placement: "a beach",
//         surrounding: "",
//         background: "",
//         lora: "RealisticNaturalScenery",
//       },
//     ],
//   },
//   {
//     title: "Outdoor Scene ",
//     list: [
//       {
//         title: "Beach ",

//         image: "https://ik.imagekit.io/7urmiszfde/Beach.png?updatedAt=1697519275490",
//         promt: "On the sand near a stunning beach",
//         placementType: "on",
//         surroundingType: "",
//         backgroundType: "",
//         product: "",
//         placement: "a beach",
//         surrounding: "",
//         background: "",
//         lora: "RealisticNaturalScenery",
//       },
//       {
//         title: "Rocks ",

//         image: "https://ik.imagekit.io/7urmiszfde/Rocks.png?updatedAt=1697518237488",
//         promt: "On a rock, around a stunning nature backdrop",
//         placementType: "on",
//         surroundingType: "",
//         backgroundType: "",
//         product: "",
//         placement: "a beach",
//         surrounding: "",
//         background: "",
//         lora: "RealisticNaturalScenery",
//       },
//       {
//         title: "Mountain ",

//         image: "https://ik.imagekit.io/7urmiszfde/Rocks.png?updatedAt=1697518237488",
//         promt: "Surrounded by a stunning Mountain backdrop",
//         placementType: "on",
//         surroundingType: "",
//         backgroundType: "",
//         product: "",
//         placement: "a beach",
//         surrounding: "",
//         background: "",
//         lora: "RealisticNaturalScenery",
//       },
//       {
//         title: "Forest ",

//         image: "https://ik.imagekit.io/7urmiszfde/Forest.png?updatedAt=1697519163718",
//         promt: "Surrounded by a lush Forest Background",
//         placementType: "on",
//         surroundingType: "",
//         backgroundType: "",
//         product: "",
//         placement: "a beach",
//         surrounding: "",
//         background: "",
//         lora: "RealisticNaturalScenery",
//       },
//       {
//         title: "Waterfall ",
//         image: "https://ik.imagekit.io/7urmiszfde/Waterfalls.png?updatedAt=1697518237119",

//         promt: "On the floor near a Waterfall",
//         placementType: "on",
//         surroundingType: "",
//         backgroundType: "",
//         product: "",
//         placement: "a beach",
//         surrounding: "",
//         background: "",
//         lora: "RealisticNaturalScenery",
//       },
//       {
//         title: "Road ",

//         image: "https://chromaticlens.com/_next/image?url=%2Fplaces%2Froad.jpeg&w=256&q=75",
//         promt: "On an empty Road",
//         placementType: "on",
//         surroundingType: "",
//         backgroundType: "",
//         product: "",
//         placement: "a beach",
//         surrounding: "",
//         background: "",
//         lora: "RealisticNaturalScenery",
//       },
//       {
//         title: "Grass ",
//         image: "https://ik.imagekit.io/7urmiszfde/Untitled%20(4).png?updatedAt=1697518624849",

//         promt: "On lush green grass",
//         placementType: "on",
//         surroundingType: "",
//         backgroundType: "",
//         product: "",
//         placement: "a beach",
//         surrounding: "",
//         background: "",
//         lora: "RealisticNaturalScenery",
//       },
//       {
//         title: "Cloudy ",

//         image: "https://ik.imagekit.io/7urmiszfde/Untitled%20(5).png?updatedAt=1697518601572",
//         promt: "Under a cloudy scene",
//         placementType: "on",
//         surroundingType: "",
//         backgroundType: "",
//         product: "",
//         placement: "a beach",
//         surrounding: "",
//         background: "",
//         lora: "RealisticNaturalScenery",
//       },
//       {
//         title: "Sunset ",
//         image: "https://ik.imagekit.io/7urmiszfde/Untitled%20(6).png?updatedAt=1697518603212",

//         promt: " In front of a Sunset",
//         placementType: "on",
//         surroundingType: "",
//         backgroundType: "",
//         product: "",
//         placement: "a beach",
//         surrounding: "",
//         background: "",
//         lora: "RealisticNaturalScenery",
//       },
     
//     ],
//   },
//   {
//     title: "Backdrops",
//     list: [
//       {
//         title: "Minimal ",

//         image: "https://ik.imagekit.io/7urmiszfde/Untitled%20(7).png?updatedAt=1697518601517",
//         promt: "Against a Minimalistic Background",
//         placementType: "on",
//         surroundingType: "",
//         backgroundType: "",
//         product: "",
//         placement: "a beach",
//         surrounding: "",
//         background: "",
//         lora: "RealisticNaturalScenery",
//       },
//       {
//         title: "Texture ",

//         image: "https://ik.imagekit.io/7urmiszfde/Untitled%20(8).png?updatedAt=1697518626376",
//         promt: "Against a Textured Wall",
//         placementType: "on",
//         surroundingType: "",
//         backgroundType: "",
//         product: "",
//         placement: "a beach",
//         surrounding: "",
//         background: "",
//         lora: "RealisticNaturalScenery",
//       },
//       {
//         title: "Fabric ",

//         image: "https://ik.imagekit.io/7urmiszfde/Untitled%20(9).png?updatedAt=1697518630173",
//         promt: "Put against a Textured Fabric",
//         placementType: "on",
//         surroundingType: "",
//         backgroundType: "",
//         product: "",
//         placement: "a beach",
//         surrounding: "",
//         background: "",
//         lora: "RealisticNaturalScenery",
//       },
//       {
//         title: "Aesthetic ",

//         image: "https://ik.imagekit.io/7urmiszfde/Untitled%20(10).png?updatedAt=1697518662057",
//         promt: "Against a an Aesthetic background",
//         placementType: "on",
//         surroundingType: "",
//         backgroundType: "",
//         product: "",
//         placement: "a beach",
//         surrounding: "",
//         background: "",
//         lora: "RealisticNaturalScenery",
//       },
//       {
//         title: "Colourful ",
//         image: "https://ik.imagekit.io/7urmiszfde/Untitled%20(11).webp?updatedAt=1697518172391",

//         promt: "Against a Colourful background",
//         placementType: "on",
//         surroundingType: "",
//         backgroundType: "",
//         product: "",
//         placement: "a beach",
//         surrounding: "",
//         background: "",
//         lora: "RealisticNaturalScenery",
//       },
//       {
//         title: "Smooth ",

//         image: "https://ik.imagekit.io/7urmiszfde/Untitled%20(12).png?updatedAt=1697518659336",
//         promt: "Put against a Smooth Fabric",
//         placementType: "on",
//         surroundingType: "",
//         backgroundType: "",
//         product: "",
//         placement: "a beach",
//         surrounding: "",
//         background: "",
//         lora: "RealisticNaturalScenery",
//       },
//       {
//         title: "Abstract ",
//         image: "https://ik.imagekit.io/7urmiszfde/Screenshot%202023-10-17%20104228.png?updatedAt=1697519576048",

//         promt: "Against a an Abstract Background",
//         placementType: "on",
//         surroundingType: "",
//         backgroundType: "",
//         product: "",
//         placement: "a beach",
//         surrounding: "",
//         background: "",
//         lora: "RealisticNaturalScenery",
//       },
//       {
//         title: "Simple ",

//         image: "https://ik.imagekit.io/7urmiszfde/Untitled%20(14).webp?updatedAt=1697518109998",
//         promt: " Against a Simple Color Background",
//         placementType: "on",
//         surroundingType: "",
//         backgroundType: "",
//         product: "",
//         placement: "a beach",
//         surrounding: "",
//         background: "",
//         lora: "RealisticNaturalScenery",
//       },
     
     
//     ],
//   },
// ];
export const TempletList = [
  {
    title: "Indoor Scene ",
    list: [
      {
        title: "Premium Living Room ",

        image: "https://ik.imagekit.io/7urmiszfde/room%20(2).webp?updatedAt=1698316221858",
        promt: "in a premium, spacious, luxuriously decorated living room with stylish decor, coffee table, classic artwork, and bright natural lighting.",
        placementType: "",
        surroundingType: "",
        backgroundType: "",
        product: "",
        placement: "",
        surrounding: "",
        background: "",
        lora: "RealisticNaturalScenery",
      },
      {
        title: "Minimal Living Room",

        image: "https://ik.imagekit.io/7urmiszfde/Minimal%20Living%20Room.webp?updatedAt=1698316221735",
        promt: "in a simple contemporary living room with minimal decor, bright natural lighting. ",
        placementType: "",
        surroundingType: "",
        backgroundType: "",
        product: "",
        placement: "a beach",
        surrounding: "",
        background: "",
        lora: "RealisticNaturalScenery",
      },
      {
        title: "Office Space ",

        image: "https://ik.imagekit.io/7urmiszfde/Office%20Space.webp?updatedAt=1698316221138",
        promt: "in a office with cubicles, muted earthy tones, soft lighting, and large windows overlooking a cityscape.",
        placementType: "",
        surroundingType: "",
        backgroundType: "",
        product: "",
        placement: "",
        surrounding: "",
        background: "",
        lora: "RealisticNaturalScenery",
      },
      {
        title: "Luxury Office Space ",

        image: "https://ik.imagekit.io/7urmiszfde/Luxury%20Office%20Space.webp?updatedAt=1698316221339",
        promt: "in a luxurious office space exuding opulence. Envision high ceilings, grand chandeliers, plush leather furniture, and rich wood accents.",
        placementType: "",
        surroundingType: "",
        backgroundType: "",
        product: "",
        placement: "a beach",
        surrounding: "",
        background: "",
        lora: "RealisticNaturalScenery",
      },
      {
        title: "Minimal Bedroom  ",

        image: "https://ik.imagekit.io/7urmiszfde/Minimal%20Bedroom.webp?updatedAt=1698316221406",
        promt: "in an minimal bedroom setting with simple wall, wooden flooring and minor decor.",
        placementType: "",
        surroundingType: "",
        backgroundType: "",
        product: "",
        placement: "",
        surrounding: "",
        background: "",
        lora: "RealisticNaturalScenery",
      },
      {
        title: "Luxury Bedroom  ",

        image: "https://ik.imagekit.io/7urmiszfde/Luxury%20Bedroom.webp?updatedAt=1698316216393",
        promt: "in an minimal bedroom setting with simple wall, wooden flooring and minor decor.",
        placementType: "",
        surroundingType: "",
        backgroundType: "",
        product: "",
        placement: "a beach",
        surrounding: "",
        background: "",
        lora: "RealisticNaturalScenery",
      },
      {
        title: "High floor Balcony",

        image: "https://ik.imagekit.io/7urmiszfde/High%20floor%20Balcony.webp?updatedAt=1698316218759",
        promt: "within a simple minimal decorated home balcony space, natural sunlight.",
        placementType: "",
        surroundingType: "",
        backgroundType: "",
        product: "",
        placement: "",
        surrounding: "",
        background: "",
        lora: "RealisticNaturalScenery",
      },
      {
        title: "Simple Balcony ",

        image: "https://ik.imagekit.io/7urmiszfde/Simple%20Balcony.webp?updatedAt=1698316219724",
        promt: "within a simple minimal decorated home balcony space, natural sunlight.",
        placementType: "",
        surroundingType: "",
        backgroundType: "",
        product: "",
        placement: "a beach",
        surrounding: "",
        background: "",
        lora: "RealisticNaturalScenery",
      },
      {
        title: "Simple Dining ",

        image: "https://ik.imagekit.io/7urmiszfde/Simple%20Dining.webp?updatedAt=1698316218494",
        promt: "in a tastefully decorated dining area, minor decor, bright sunlight ",
        placementType: "",
        surroundingType: "",
        backgroundType: "",
        product: "",
        placement: "",
        surrounding: "",
        background: "",
        lora: "RealisticNaturalScenery",
      },
      {
        title: "Luxury Dining",

        image: "https://ik.imagekit.io/7urmiszfde/Luxury%20Dining.webp?updatedAt=1698316210181",
        promt: "in an pulent and lavishly decorated dining space, featuring rich textures, elegant lighting, and meticulously curated decor.",
        placementType: "",
        surroundingType: "",
        backgroundType: "",
        product: "",
        placement: "a beach",
        surrounding: "",
        background: "",
        lora: "RealisticNaturalScenery",
      }, {
        title: "Kitchen ",

        image: "https://ik.imagekit.io/7urmiszfde/Kitchen%20(2).webp?updatedAt=1698316211144",
        promt: "in a modern, well-equipped kitchen, minimum kitchen decor, under-cabinet lighting.",
        placementType: "",
        surroundingType: "",
        backgroundType: "",
        product: "",
        placement: "",
        surrounding: "",
        background: "",
        lora: "RealisticNaturalScenery",
      },
      {
        title: "Home Gym ",

        image: "https://ik.imagekit.io/7urmiszfde/Home%20Gym.webp?updatedAt=1698316216433",
        promt: "in a well-organized, minimal, home gym space",
        placementType: "",
        surroundingType: "",
        backgroundType: "",
        product: "",
        placement: "a beach",
        surrounding: "",
        background: "",
        lora: "RealisticNaturalScenery",
      }, {
        title: "Entertainment Space",

        image: "https://ik.imagekit.io/7urmiszfde/Entertainment%20Space.webp?updatedAt=1698316210293",
        promt: "in a futuristic entertainment space, with bright lighting, sleek, minimalist furnishings, immersive sound systems and speakers around.",
        placementType: "",
        surroundingType: "",
        backgroundType: "",
        product: "",
        placement: "",
        surrounding: "",
        background: "",
        lora: "RealisticNaturalScenery",
      },
      {
        title: "Indoor Garden Room",

        image: "https://ik.imagekit.io/7urmiszfde/Indoor%20Garden%20Room.webp?updatedAt=1698316245405",
        promt: "in an indoor garden oasis, surrounded by lush plants, verdant greenery, cascading vines, bright natural light",
        placementType: "",
        surroundingType: "",
        backgroundType: "",
        product: "",
        placement: "",
        surrounding: "",
        background: "",
        lora: "RealisticNaturalScenery",
      },
      {
        title: "Library",

        image: "https://ik.imagekit.io/7urmiszfde/Library.webp?updatedAt=1698316219739",
        promt: "in a cozy library filled with books and reading nooks, spacious, natural light.",
        placementType: "",
        surroundingType: "",
        backgroundType: "",
        product: "",
        placement: "",
        surrounding: "",
        background: "",
        lora: "RealisticNaturalScenery",
      },
      {
        title: "Home Theater",

        image: "https://ik.imagekit.io/7urmiszfde/Home%20Theater.webp?updatedAt=1698316215601",
        promt: "in a dedicated home theater room plush seating.",
        placementType: "",
        surroundingType: "",
        backgroundType: "",
        product: "",
        placement: "",
        surrounding: "",
        background: "",
        lora: "RealisticNaturalScenery",
      },
      
    ],
  },
  {
    title: "Outdoor Scene ",
    list: [
      {
        title: "Garden Oasis ",

        image: "https://ik.imagekit.io/7urmiszfde/Garden%20Oasis.webp?updatedAt=1698316239789",
        promt: "in a picturesque garden oasis, surrounded by lush greenery, vibrant potted plants, and bathed in bright, natural lighting",
        placementType: "on",
        surroundingType: "",
        backgroundType: "",
        product: "",
        placement: "a beach",
        surrounding: "",
        background: "",
        lora: "RealisticNaturalScenery",
      },
      {
        title: "Beachside ",

        image: "https://ik.imagekit.io/7urmiszfde/Beachside.webp?updatedAt=1698316237620",
        promt: "against the stunning backdrop of a sun-soaked beach, with pristine sand, azure sea, and gently swaying palm trees",
        placementType: "on",
        surroundingType: "",
        backgroundType: "",
        product: "",
        placement: "a beach",
        surrounding: "",
        background: "",
        lora: "RealisticNaturalScenery",
      },
      {
        title: "Luxury Coastal ",

        image: "https://ik.imagekit.io/7urmiszfde/Luxury%20Coastal.webp?updatedAt=1698316242387",
        promt: "on a wooden deck, in luxurious coastal setting, surrounded by natural plants natural daylight",
        placementType: "on",
        surroundingType: "",
        backgroundType: "",
        product: "",
        placement: "a beach",
        surrounding: "",
        background: "",
        lora: "RealisticNaturalScenery",
      },
      {
        title: "Urban Rooftop ",

        image: "https://ik.imagekit.io/7urmiszfde/Urban%20Rooftop.webp?updatedAt=1698316236937",
        promt: "on a chic urban rooftop, night, breathtaking city skyline, bokeh, studio bright light",
        placementType: "on",
        surroundingType: "",
        backgroundType: "",
        product: "",
        placement: "a beach",
        surrounding: "",
        background: "",
        lora: "RealisticNaturalScenery",
      },
      {
        title: "Lakeside ",
        image: "https://ik.imagekit.io/7urmiszfde/Lakeside.webp?updatedAt=1698316235116",

        promt: "besides clam lakeside, calm waters, towering trees, natural soft light",
        placementType: "on",
        surroundingType: "",
        backgroundType: "",
        product: "",
        placement: "a beach",
        surrounding: "",
        background: "",
        lora: "RealisticNaturalScenery",
      },
      {
        title: "Picnic Spot ",

        image: "https://ik.imagekit.io/7urmiszfde/Picnic%20Spot.webp?updatedAt=1698316237371",
        promt: "in a natural picnic setting, lush green grassy mountains, minimal picnic decor, natural soft light",
        placementType: "on",
        surroundingType: "",
        backgroundType: "",
        product: "",
        placement: "a beach",
        surrounding: "",
        background: "",
        lora: "RealisticNaturalScenery",
      },
      {
        title: "Rocky terrain ",
        image: "https://ik.imagekit.io/7urmiszfde/Rocky%20terrain.webp?updatedAt=1698316222047",

        promt: "at a rugged and rocky terrain environment, surrounded by small leafy plants, natural soft sunlight",
        placementType: "on",
        surroundingType: "",
        backgroundType: "",
        product: "",
        placement: "a beach",
        surrounding: "",
        background: "",
        lora: "RealisticNaturalScenery",
      },
      {
        title: "Dense Forest ",

        image: "https://ik.imagekit.io/7urmiszfde/Dense%20Forest.webp?updatedAt=1698316245243",
        promt: "in dense forest, surrounded by towering trees.",
        placementType: "on",
        surroundingType: "",
        backgroundType: "",
        product: "",
        placement: "a beach",
        surrounding: "",
        background: "",
        lora: "RealisticNaturalScenery",
      },
      {
        title: "Mountain ",
        image: "https://ik.imagekit.io/7urmiszfde/Mountain.webp?updatedAt=1698316222927",

        promt: "on a rustic wooden table, camping setting, with a majestic mountain backdrop, natural overcasting light",
        placementType: "on",
        surroundingType: "",
        backgroundType: "",
        product: "",
        placement: "a beach",
        surrounding: "",
        background: "",
        lora: "RealisticNaturalScenery",
      },
      {
        title: "Waterfall ",
        image: "https://ik.imagekit.io/7urmiszfde/Waterfall.webp?updatedAt=1698316226492",

        promt: "against the backdrop of a mesmerizing waterfall, wooden bridge, lush, vibrant vegetation, natural overcasting light ",
        placementType: "on",
        surroundingType: "",
        backgroundType: "",
        product: "",
        placement: "a beach",
        surrounding: "",
        background: "",
        lora: "RealisticNaturalScenery",
      },
      {
        title: " Raining",
        image: "https://ik.imagekit.io/7urmiszfde/Raining.webp?updatedAt=1698316224505",

        promt: "on a wet flooring, courtyard, surround the scene with raindrops, lush potted plants, and vintage lampposts, soft natural overcast light. ",
        placementType: "on",
        surroundingType: "",
        backgroundType: "",
        product: "",
        placement: "a beach",
        surrounding: "",
        background: "",
        lora: "RealisticNaturalScenery",
      },
      {
        title: "Bamboo Forest  ",
        image: "https://ik.imagekit.io/7urmiszfde/Bamboo%20Forest.webp?updatedAt=1698316239435",

        promt: "on a bamboo table, lush bamboo forest with bamboo shoots, dappled sunlight. ",
        placementType: "on",
        surroundingType: "",
        backgroundType: "",
        product: "",
        placement: "a beach",
        surrounding: "",
        background: "",
        lora: "RealisticNaturalScenery",
      },
      {
        title: "Snowy  ",
        image: "https://ik.imagekit.io/7urmiszfde/Snowy.webp?updatedAt=1698316241491",

        promt: "against a snow-covered mountain, towering trees, natural winter sunlight ",
        placementType: "on",
        surroundingType: "",
        backgroundType: "",
        product: "",
        placement: "a beach",
        surrounding: "",
        background: "",
        lora: "RealisticNaturalScenery",
      },
      {
        title: "Moss  ",
        image: "https://ik.imagekit.io/7urmiszfde/Moss.webp?updatedAt=1698316239784",

        promt: "against a backdrop of natural moss, rustic stones and rock, delicate woodland flowers and plants. ",
        placementType: "on",
        surroundingType: "",
        backgroundType: "",
        product: "",
        placement: "a beach",
        surrounding: "",
        background: "",
        lora: "RealisticNaturalScenery",
      },
      {
        title: "Sports Arena  ",
        image: "https://ik.imagekit.io/7urmiszfde/Sports%20Arena.webp?updatedAt=1698316240395",

        promt: "at a sports ground with vibrant colors, cheering crowds, stadium bright light ",
        placementType: "on",
        surroundingType: "",
        backgroundType: "",
        product: "",
        placement: "a beach",
        surrounding: "",
        background: "",
        lora: "RealisticNaturalScenery",
      },
      {
        title: "Garden  ",
        image: "https://ik.imagekit.io/7urmiszfde/Garden.webp?updatedAt=1698316242986",

        promt: "in a charming outdoor gathering in a serene garden, lush greenery, vibrant potted plants, bright natural lighting ",
        placementType: "on",
        surroundingType: "",
        backgroundType: "",
        product: "",
        placement: "a beach",
        surrounding: "",
        background: "",
        lora: "RealisticNaturalScenery",
      },
     
    ],
  },
  {
    title: "On Platforms ",
    list: [
      {
        title: "Simple Platform ",

        image: "https://ik.imagekit.io/7urmiszfde/Simple%20Platform.webp?updatedAt=1698333525653",
        promt: "on a pristine white circular platform, spotless studio backdrop, minimalist atmosphere, studio lighting",
        placementType: "on",
        surroundingType: "",
        backgroundType: "",
        product: "",
        placement: "a beach",
        surrounding: "",
        background: "",
        lora: "RealisticNaturalScenery",
      },
      {
        title: "Marble ",

        image: "https://ik.imagekit.io/7urmiszfde/Marble.webp?updatedAt=1698333165302",
        promt: "placed on a lifted white marble, natural light, photoshoot",
        placementType: "on",
        surroundingType: "",
        backgroundType: "",
        product: "",
        placement: "a beach",
        surrounding: "",
        background: "",
        lora: "RealisticNaturalScenery",
      },
      {
        title: "Rustic Wodeen  ",

        image: "https://ik.imagekit.io/7urmiszfde/Rustic%20Wodeen.webp?updatedAt=1698333525271",
        promt: "placed on a rustic wooden platform",
        placementType: "on",
        surroundingType: "",
        backgroundType: "",
        product: "",
        placement: "a beach",
        surrounding: "",
        background: "",
        lora: "RealisticNaturalScenery",
      },
      {
        title: "Sand ",

        image: "https://ik.imagekit.io/7urmiszfde/Sand.webp?updatedAt=1698333524431",
        promt: "buried in the sand surrounded with few shells and flowers.",
        placementType: "on",
        surroundingType: "",
        backgroundType: "",
        product: "",
        placement: "a beach",
        surrounding: "",
        background: "",
        lora: "RealisticNaturalScenery",
      },
      {
        title: "Podium ",

        image: "https://ik.imagekit.io/7urmiszfde/Podium.webp?updatedAt=1698333524906",
        promt: "on an elegant white circular podium with aesthetics textured wall. ",
        placementType: "on",
        surroundingType: "",
        backgroundType: "",
        product: "",
        placement: "a beach",
        surrounding: "",
        background: "",
        lora: "RealisticNaturalScenery",
      },
      {
        title: "Coffee Table ",

        image: "https://ik.imagekit.io/7urmiszfde/Coffee%20Table.webp?updatedAt=1698333523053",
        promt: "on a stylish coffee table surrounded by small plants.",
        placementType: "on",
        surroundingType: "",
        backgroundType: "",
        product: "",
        placement: "a beach",
        surrounding: "",
        background: "",
        lora: "RealisticNaturalScenery",
      },
      {
        title: "Platform on Water",

        image: "https://ik.imagekit.io/7urmiszfde/Platform%20on%20Water.webp?updatedAt=1698333526564",
        promt: "on a circular platform surrounded by water lake and tiny flowers",
        placementType: "",
        surroundingType: "",
        backgroundType: "",
        product: "",
        placement: "",
        surrounding: "",
        background: "",
        lora: "RealisticNaturalScenery",
      },
      {
        title: "Wet Surface",

        image: "https://ik.imagekit.io/7urmiszfde/Wet%20Surface.webp?updatedAt=1698333523738",
        promt: "placed on a wet reflective surface surrounded by rain, in front of a spotlight.  ",
        placementType: "",
        surroundingType: "",
        backgroundType: "",
        product: "",
        placement: "",
        surrounding: "",
        background: "",
        lora: "RealisticNaturalScenery",
      }, {
        title: "Acrylic platform",

        image: "https://ik.imagekit.io/7urmiszfde/Acrylic%20platform.webp?updatedAt=1698333523054",
        promt: "placed on a matte black acrylic platform  ",
        placementType: "",
        surroundingType: "",
        backgroundType: "",
        product: "",
        placement: "",
        surrounding: "",
        background: "",
        lora: "RealisticNaturalScenery",
      }, {
        title: "Stone",

        image: "https://ik.imagekit.io/7urmiszfde/Stone.webp?updatedAt=1698333521198",
        promt: "placed on a natural stone platform, surrounded by rocks, natural sunlight ",
        placementType: "",
        surroundingType: "",
        backgroundType: "",
        product: "",
        placement: "",
        surrounding: "",
        background: "",
        lora: "RealisticNaturalScenery",
      }, {
        title: "Velvet",

        image: "https://ik.imagekit.io/7urmiszfde/Velvet.webp?updatedAt=1698333518847",
        promt: "placed on a plush velvet platform, surrounded by tiny flower petals ",
        placementType: "",
        surroundingType: "",
        backgroundType: "",
        product: "",
        placement: "",
        surrounding: "",
        background: "",
        lora: "RealisticNaturalScenery",
      }, {
        title: "Wooden Dock Lake",

        image: "https://ik.imagekit.io/7urmiszfde/Wooden%20Dock%20Lake.webp?updatedAt=1698333514597",
        promt: "on top of a wooden dock overlooking a tranquil lake.  ",
        placementType: "",
        surroundingType: "",
        backgroundType: "",
        product: "",
        placement: "",
        surrounding: "",
        background: "",
        lora: "RealisticNaturalScenery",
      }, {
        title: "Rug",

        image: "https://ik.imagekit.io/7urmiszfde/Rug.webp?updatedAt=1698333520778",
        promt: "on a plush, furry rug.  ",
        placementType: "",
        surroundingType: "",
        backgroundType: "",
        product: "",
        placement: "",
        surrounding: "",
        background: "",
        lora: "RealisticNaturalScenery",
      }, {
        title: "Silver Stage",

        image: "https://ik.imagekit.io/7urmiszfde/Silver%20Stage.webp?updatedAt=1698333518286",
        promt: "on a reflective performance stage.  ",
        placementType: "",
        surroundingType: "",
        backgroundType: "",
        product: "",
        placement: "",
        surrounding: "",
        background: "",
        lora: "RealisticNaturalScenery",
      }, {
        title: "Rock & River",

        image: "https://ik.imagekit.io/7urmiszfde/Rock%20&%20River.webp?updatedAt=1698333521200",
        promt: "on a rock surrounded by trees, in front of a canyon and river” ",
        placementType: "",
        surroundingType: "",
        backgroundType: "",
        product: "",
        placement: "",
        surrounding: "",
        background: "",
        lora: "RealisticNaturalScenery",
      }, {
        title: "Staricase",

        image: "https://ik.imagekit.io/7urmiszfde/Staricase.webp?updatedAt=1698333521734",
        promt: "on on a marble staircase.  ",
        placementType: "",
        surroundingType: "",
        backgroundType: "",
        product: "",
        placement: "",
        surrounding: "",
        background: "",
        lora: "RealisticNaturalScenery",
      }, {
        title: "Kitchen Counter",

        image: "https://ik.imagekit.io/7urmiszfde/Kitchen%20Counter.webp?updatedAt=1698333527026",
        promt: "on a modern kitchen counter.  ",
        placementType: "",
        surroundingType: "",
        backgroundType: "",
        product: "",
        placement: "",
        surrounding: "",
        background: "",
        lora: "RealisticNaturalScenery",
      }, {
        title: "Rippling Water",

        image: "https://ik.imagekit.io/7urmiszfde/Rippling%20Water.webp?updatedAt=1698333183109",
        promt: "emerging from rippling water.  ",
        placementType: "",
        surroundingType: "",
        backgroundType: "",
        product: "",
        placement: "",
        surrounding: "",
        background: "",
        lora: "RealisticNaturalScenery",
      }, {
        title: "Neon Podium",

        image: "https://ik.imagekit.io/7urmiszfde/Neon%20Podium.webp?updatedAt=1698333514900",
        promt: "placed on a neon-lit platform with futuristic aesthetic.  ",
        placementType: "",
        surroundingType: "",
        backgroundType: "",
        product: "",
        placement: "",
        surrounding: "",
        background: "",
        lora: "RealisticNaturalScenery",
      }, {
        title: "Grass Bed",

        image: "https://ik.imagekit.io/7urmiszfde/Grass%20Bed.webp?updatedAt=1698333516751",
        promt: "product on a grass bed, surrounded by small flowers and rocks ",
        placementType: "",
        surroundingType: "",
        backgroundType: "",
        product: "",
        placement: "",
        surrounding: "",
        background: "",
        lora: "RealisticNaturalScenery",
      }, {
        title: "Studio Podium",

        image: "https://ik.imagekit.io/7urmiszfde/Studio%20Podium.webp?updatedAt=1698333514591",
        promt: "on a standard podium with soft, flattering lighting, creating a studio look.  ",
        placementType: "",
        surroundingType: "",
        backgroundType: "",
        product: "",
        placement: "",
        surrounding: "",
        background: "",
        lora: "RealisticNaturalScenery",
      }, 
    ],
  },
 
  {
    title: "Backdrops",
    list: [
      {
        title: "Vinyl ",

        image: "https://ik.imagekit.io/7urmiszfde/Vinyl.webp?updatedAt=1698334188864",
        promt: "against a professional vinyl backdrop, with soft diffused lighting",
        placementType: "on",
        surroundingType: "",
        backgroundType: "",
        product: "",
        placement: "a beach",
        surrounding: "",
        background: "",
        lora: "RealisticNaturalScenery",
      },
      {
        title: "Fabric ",

        image: "https://ik.imagekit.io/7urmiszfde/Fabric.webp?updatedAt=1698334207986",
        promt: "on a simple plain fabric, soft warm diffused lighting",
        placementType: "on",
        surroundingType: "",
        backgroundType: "",
        product: "",
        placement: "a beach",
        surrounding: "",
        background: "",
        lora: "RealisticNaturalScenery",
      },
      {
        title: "Stone Wall ",

        image: "https://ik.imagekit.io/7urmiszfde/Stone%20Wall.webp?updatedAt=1698334168250",
        promt: "placed on a textured natural stone wall with gentle, natural light casting soft shadows",
        placementType: "on",
        surroundingType: "",
        backgroundType: "",
        product: "",
        placement: "a beach",
        surrounding: "",
        background: "",
        lora: "RealisticNaturalScenery",
      },
      {
        title: "Foliage ",

        image: "https://ik.imagekit.io/7urmiszfde/Foliage.webp?updatedAt=1698334211052",
        promt: "in a lush garden setting, vibrant greenery, colorful blooms, soft bring sunlight",
        placementType: "on",
        surroundingType: "",
        backgroundType: "",
        product: "",
        placement: "a beach",
        surrounding: "",
        background: "",
        lora: "RealisticNaturalScenery",
      },
      {
        title: "Decorative tile ",
        image: "https://ik.imagekit.io/7urmiszfde/Decorative%20tile.webp?updatedAt=1698334188914",

        promt: "in front of an intricately designed tile backdrop, with ornate patterns and rich colors, natural soft lighting",
        placementType: "on",
        surroundingType: "",
        backgroundType: "",
        product: "",
        placement: "a beach",
        surrounding: "",
        background: "",
        lora: "RealisticNaturalScenery",
      },
      {
        title: "Wallpaper ",

        image: "https://ik.imagekit.io/7urmiszfde/Wallpaper%20(1).webp?updatedAt=1698334215559",
        promt: " against a backdrop of wallpapers with vareity of dark and soft pattern and style with natural soft sunlight",
        placementType: "on",
        surroundingType: "",
        backgroundType: "",
        product: "",
        placement: "a beach",
        surrounding: "",
        background: "",
        lora: "RealisticNaturalScenery",
      },
      {
        title: "Aesthetics  ",
        image: "https://ik.imagekit.io/7urmiszfde/Aesthetics.webp?updatedAt=1698334224447",

        promt: "with a backdrop that embodies artistic aesthetics",
        placementType: "on",
        surroundingType: "",
        backgroundType: "",
        product: "",
        placement: "a beach",
        surrounding: "",
        background: "",
        lora: "RealisticNaturalScenery",
      },
      {
        title: "Wooden ",

        image: "https://ik.imagekit.io/7urmiszfde/Wooden.webp?updatedAt=1698334188960",
        promt: "on a simple wooden table, natural sunlight ",
        placementType: "on",
        surroundingType: "",
        backgroundType: "",
        product: "",
        placement: "a beach",
        surrounding: "",
        background: "",
        lora: "RealisticNaturalScenery",
      },
      
      {
        title: "Bamboo ",

        image: "https://ik.imagekit.io/7urmiszfde/Bamboo.webp?updatedAt=1698334208556",
        promt: "on a simple platform, in front of a bamboo backdrop.  ",
        placementType: "",
        surroundingType: "",
        backgroundType: "",
        product: "",
        placement: "",
        surrounding: "",
        background: "",
        lora: "RealisticNaturalScenery",
      },
      {
        title: "Coloured Backdrop ",

        image: "https://ik.imagekit.io/7urmiszfde/Coloured%20Backdrop.webp?updatedAt=1698334165322",
        promt: "against a Coloured backdrops with studio lighting ",
        placementType: "",
        surroundingType: "",
        backgroundType: "",
        product: "",
        placement: "",
        surrounding: "",
        background: "",
        lora: "RealisticNaturalScenery",
      },
      {
        title: "Abstracts ",

        image: "https://ik.imagekit.io/7urmiszfde/Abstracts%20(1).webp?updatedAt=1698334166271",
        promt: "against abstract and artistic backdrops, natural bright lighting  ",
        placementType: "",
        surroundingType: "",
        backgroundType: "",
        product: "",
        placement: "",
        surrounding: "",
        background: "",
        lora: "RealisticNaturalScenery",
      }, {
        title: "Leather  ",

        image: "https://ik.imagekit.io/7urmiszfde/Leather.webp?updatedAt=1698334252614",
        promt: "placed on a simple platform with backdrop of textured leather. ",
        placementType: "",
        surroundingType: "",
        backgroundType: "",
        product: "",
        placement: "",
        surrounding: "",
        background: "",
        lora: "RealisticNaturalScenery",
      }, {
        title: " Flower Petals ",

        image: "https://ik.imagekit.io/7urmiszfde/Flower%20Petals.webp?updatedAt=1698334191325",
        promt: "on a simple platform ,surrounded by falling flower petals, natural bright light.  ",
        placementType: "",
        surroundingType: "",
        backgroundType: "",
        product: "",
        placement: "",
        surrounding: "",
        background: "",
        lora: "RealisticNaturalScenery",
      }, {
        title: "Gradient ",

        image: "https://ik.imagekit.io/7urmiszfde/Gradient.webp?updatedAt=1698334188909",
        promt: " in front of fluid 3D background with soft lighting  ",
        placementType: "",
        surroundingType: "",
        backgroundType: "",
        product: "",
        placement: "",
        surrounding: "",
        background: "",
        lora: "RealisticNaturalScenery",
      }, {
        title: "Simple Studio ",

        image: "https://ik.imagekit.io/7urmiszfde/Simple%20Studio.webp?updatedAt=1698334164463",
        promt: "set against a studio backdrop with studio lighting from top right side.  ",
        placementType: "",
        surroundingType: "",
        backgroundType: "",
        product: "",
        placement: "",
        surrounding: "",
        background: "",
        lora: "RealisticNaturalScenery",
      },{
        title: "Ice  ",

        image: "https://ik.imagekit.io/7urmiszfde/Ice.webp?updatedAt=1698334167014",
        promt: "on reflective surface, against snowy mountains and sunny skies in the background, natural light  ",
        placementType: "",
        surroundingType: "",
        backgroundType: "",
        product: "",
        placement: "",
        surrounding: "",
        background: "",
        lora: "RealisticNaturalScenery",
      },{
        title: "Marble ",

        image: "https://ik.imagekit.io/7urmiszfde/Screenshot%202023-10-26%20211954.webp?updatedAt=1698335486012",
        promt: "against a marble wall studio backdrop, bright natural lighting  ",
        placementType: "",
        surroundingType: "",
        backgroundType: "",
        product: "",
        placement: "",
        surrounding: "",
        background: "",
        lora: "RealisticNaturalScenery",
      },
     
     
    ],
  },
];